name: Deploy Dataflow Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install apache-beam[gcp]

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Run Dataflow Pipeline
      run: |
        python -m dataflow_pipeline.pipeline \
          --runner=DataflowRunner \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --region=us-central1 \
          --temp_location=gs://${{secrets.GCP_TEMP_BUCKET}}/temp \
          --input_topic=projects/${{ secrets.GCP_PROJECT_ID }}/topics/${{secrets.GCP_TOPIC}} \
          --output_bucket=${{secrets.GCP_BUCKET}} \
          --setup_file=./setup.py
